GET http://localhost:9200/census_2020/_search
content-type: application/json; charset=UTF-8

{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "geo_shape": {
          "geometry": {
            "shape": {
              "type": "point",
              "coordinates": [ -73.985428, 40.748817 ]
            },
            "relation": "contains"
          }
        }
      }
    }
  }
}