### simple query
PUT http://dev.dictadata.net:9200/foo_schema_2
Content-Type: application/json

{
  "settings": {
    "index.number_of_shards": 3,
    "index.number_of_replicas": 1,
    "index.write.wait_for_active_shards": "2"
  },
  "mappings": {
    "_meta": {
      "my_version": "1.0.1"
    },
    "date_detection": false,
    "dynamic_templates": [
      {
        "strings_as_keyword": {
          "mapping": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "match_mapping_type": "string"
        }
      }
    ],
    "properties": {
      "Foo": {
        "type": "keyword"
      },
      "Bar": {
        "type": "text"
      },
      "Baz": {
        "type": "integer"
      },
      "Fobe": {
        "type": "double"
      },
      "Dt Test": {
        "type": "date"
      },
      "enabled": {
        "type": "boolean"
      }
    }
  }
}
